### ISSUE TITLE
Gestione Personale, livelli  dipendenti (qualifications)

### ISSUE THREAD

**Issue by lucanatalegov** [consiglionazionaledellericerche/epas#12]
In ePAS sono definiti 10 livelli  predefiniti.
E' possibile aggiungere altri livelli  con un descrizione  personalizzata e con una qualifica compresa tra 1 e 10.

Grazie

**Comment by criluc** [comment]
Possiamo aggiungere una CRUD per la gestione delle qualifiche che corrispondono poi a questa alla [Entity Qualification](https://github.com/consiglionazionaledellericerche/epas/blob/main/app/models/Qualification.java).
Sarà comunque obbligatorio specificare un livello ([attributo `int qualification`](https://github.com/consiglionazionaledellericerche/epas/blob/main/app/models/Qualification.java#L57)) che corrisponde ad un numero intero, perché questo numero è poi utilizzato per differenziare i livelli dirigenziali (quelli con livello <=3), vedi  
([metodo `isTopQualification`](https://github.com/consiglionazionaledellericerche/epas/blob/main/app/models/Qualification.java#L66)).

E' comunque da tenere in considerazione che in ePAS sono cablati nel codice alcuni comportamenti per i livelli I-III che dipendono dal contratto nazionale degli pubblici di ricerca. In particolare per questi livelli (I-III) non esiste una scadenza del monte orario e non possono prendere ore di straordinario, turni, reperibilità, oltre al fatto che alcuni flussi di approvazione non esistono ma diventano flussi informativi (i livelli I-III per esempio non chiedono le ferie ma le comunicano).

Fatte queste precisazioni serve comunque questa CRUD per le qualifiche? Se può essere utile la possiamo mettere in scaletta per le prossime versioni.

**Comment by lucanatalegov** [comment]
Si Grazie.
Noi pensiamo di non utilizzare i livelli da I - III ma solo i livelli successivi.
Abbimo notato che per i livelli da I - III è comunque presente, nella richista dei flussi, l'approvazione delle ferie, compensativi e permessi da parte del responsabile di gruppo e sede che , invece, non è presente per i livelli IX e X.

Per il momento possimo procedere modificando la colonna description tabella qualifications e aggiungere altre righe ? ( in questo caso siamo obbligati ad usare la qualification da 1 a 10)
