### ISSUE TITLE
epas: modifica della root path 

### ISSUE THREAD

**Issue by lucanatalegov** [consiglionazionaledellericerche/epas#13]
Buongiono dopo la modifica del root path ( per esempio /epas ) dopo la pagina di login la redirect è fatta senza la root path
Dopo la login devo  modificare l'url e aggiungere 

/epas/stampings/stampings?month=5&year=2023

per visualizzare la prima pagina. 

Grazie

**Comment by criluc** [comment]
Buongiorno,
hai modificato il parametro del docker-compose.yml "HTTP_PATH"? E' questo il parametro che controlla la costruzione del path generato dell'applicazione.
Se il parametro è stato impostato correttamente all'avvio del container nei log dovresti trovare qualcosa del genere

Attaching to epas
epas        | ePas Protocol set to http
epas        | Backup del database non attivo.
epas        | HTTP_PATH presente: /epas

Se non è presente il log "epas        | HTTP_PATH presente: /epas" vuol dire che il parametro HTTP_PATH non è correttamente impostato a /epas.

Dalle prove che abbiamo fatto, con il parametro HTTP_PATH impostato, non siamo riusciti a riprodurre il problema da te riportato.

**Comment by lucanatalegov** [comment]
I parametri sono


protocol=https
http_path=/epas

nel file di log nonostante io abbia messo il 
log_level ad ALL   e
Appenders= file 

nel file non è presente la stringa 

epas | HTTP_PATH


La versione di epas attiva è la 2.6.5

Grazie

**Comment by criluc** [comment]
Il log `epas | HTTP_PATH presente: /epas` viene inviato sullo standard output, può darsi non sia presente nel file di log, dovresti poterlo trovare con un comando tipo questo:

`$ docker-compose logs --tail=1000 | grep HTTP_PATH`

che dovrebbe avere un output tipo questo:

`epas        | HTTP_PATH presente: /epas`

Magari verifica anche tramite il comando :

`docker-compose config | grep HTTP_PATH `

che l'impostazione tramite docker-compose.yml ed eventuale .env sia avvenuta correttamente, in questo caso l'output del comando precedente dovrebbe essere:

`      HTTP_PATH: /epas`

**Comment by lucanatalegov** [comment]
Noi abbiamo installo epas in uno stack docker questo è il log del servizio

opadmin@docker001:/app/mit4me$ docker service logs epas_epasd
epas_epasd.1.mzw4sf8q822p@docker004    | ePas Protocol set to https
epas_epasd.1.mzw4sf8q822p@docker004    | Backup del database non attivo.
**epas_epasd.1.mzw4sf8q822p@docker004    | HTTP_PATH presente: /epas**
epas_epasd.1.mzw4sf8q822p@docker004    | Evoluzioni disabilitate dalla configurazione: EVOLUTIONS_ENABLED=false
epas_epasd.1.mzw4sf8q822p@docker004    | Avvio ePas...
epas_epasd.1.mzw4sf8q822p@docker004    | :: loading settings :: url = jar:file:/opt/play/play-1.5.3/framework/lib/ivy-2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
epas_epasd.1.mzw4sf8q822p@docker004    | WARNING: An illegal reflective access operation has occurred
epas_epasd.1.mzw4sf8q822p@docker004    | WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v7.Java7$1 (file:/opt/play/play-1.5.3/framework/lib/groovy-2.5.3.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
epas_epasd.1.mzw4sf8q822p@docker004    | WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v7.Java7$1
epas_epasd.1.mzw4sf8q822p@docker004    | WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
epas_epasd.1.mzw4sf8q822p@docker004    | WARNING: All illegal access operations will be denied in a future release

**Comment by criluc** [comment]
> Ho eseguito altri test e nel caso di login locale funziona tutto regolarmente dopo la post di **login** è inviato al client la pagina /epas
> 
> mentre nel caso di autenticazione con ldap dopo la post di **autenticate** al client non è inviato la /epas ma la /.
> 
> Grazie ![epas_ldap](https://user-images.githubusercontent.com/114504271/242009147-1cfee417-b978-48b5-a50a-5df3c9bb48ba.png) ![epas_locale](https://user-images.githubusercontent.com/114504271/242009152-f23c62de-2395-4c76-b9e0-33d2393884da.png)

ok, con queste info aggiuntive ho individuato il problema. 
Abbiamo corretto il problema, la correzione a partire dalla versione 2.6.7 che dovrebbe essere pubblicata a giorni.

**Comment by lucanatalegov** [comment]
Noi abbiamo installato la versione 2.6.5 possimo fare il passagio diretto alla 2.6.7 o dobbiamo fare prima il passagio alla 2.6.6?
Grazie

**Comment by criluc** [comment]
E' disponibile la versione 2.6.7 che dovrebbe risolvere il problema riportato in questa segnalazione.
Potete passare direttamente dalla 2.6.5 alla 2.6.7.
