### ISSUE TITLE
Sostitusione dell string CNR

### ISSUE THREAD

**Issue by lucanatalegov** [consiglionazionaledellericerche/epas#14]
In alune pagine compare la stringa CNR è possibile sostituirla con la 

company.code

Grazie

**Comment by criluc** [comment]
Ok, andrà online con la versione 2.6.7.

**Comment by criluc** [comment]
> Nel manuale non trovato una procedura di upgrade. Mi potreste indicare come fare la procedura di upgrade?

`docker-compose pull && docker-compose up -d`

Ogni immagine contiene già un meccanismo di aggiornamento dei componenti necessari, tra cui le evoluzioni del database. Se avete più istanze è necessario che una abbia il parametro EVOLUTIONS_ENABLED=true e che questa immagine sia aggiornata per prima, in modo che le altre istanze si ritrovino il DB già aggiornato.

**Comment by criluc** [comment]
E' disponibile la versione 2.6.7 che sostituisce dove possibile la stringa CNR con company.code.
