### ISSUE TITLE
# Errore conteggio ore in ePAS per Gennaio di ogni anno

### ISSUE THREAD

**Issue by DavFra94** [consiglionazionaledellericerche/epas#142]
Salve, a seguito di verifica mi sembra di riscontrare un bug nel momento in cui si effettuano ore in negativo nel solo mese di Gennaio.
Di fatto nel box delle ore residue del mese corrente risultano in eccesso i minuti che invece dovrebbero essere a differenza. 
Allego screenshot di esempio, profilo CTER:
![ePAS bug](https://github.com/consiglionazionaledellericerche/epas/assets/151858507/d1275126-7592-46c7-8fb3-de3f2e2870af)
Grazie e buon lavoro.

**Comment by criluc** [comment]
Il residuo del mese positivo, corrisponde alla somma delle differenze positive di tutti i giorni., quindi il dato mostrato nella screenshot è corretto.
Mentre il progressivo finale del mese corrisponde a alla somma di tutte le differenze (sia quelle positive che negative).
Il residuo del mese positivo è volutamente trattato diversamente dal progressivo finale perché è spesso utilizzato come limite massimo delle ore pagabili come straordinario, perché le giornate con differenza negativa possono essere invece imputate come recupero delle ore da anno precedente o dai mesi precedenti dello stesso anno.

**Comment by DavFra94** [comment]
Grazie per la risposta, ma le faccio notare che per come è stato indicizzata, la somma dei soli residui positivi riportata nel box di destra non corrisponde con la somma delle differenze positive riportate nella colonna "differenze", generando un eccesso di ore lavorate.

**Comment by criluc** [comment]
La controprova è che se al progressivo finale di 19:10, sommiamo le differenze negative (0:08), il totale di quelle positive è appunto 19:18.  Cosa non torna?

**Comment by DavFra94** [comment]
A mio avviso le differenze negative non possono essere sommate insieme ai residui positivi, perché si cerca di sommare ore ore non lavorate (uscita anticipata) con ore effettivamente lavorate (residui positivi). Non mi sembra logico che fra le ore disponibili per straordinario siano imputabili anche quelle non lavorate. Opinione personale.

**Comment by DavFra94** [comment]
In questo modo, se nota bene, nel box "Situazione residuo derivante dall'anno precedente" mi sono state correttamente detratti gli 8 minuti, tuttavia poi lei mi dice che le differenze negative vengono nuovamente sommate ai residui positivi, generando materialmente un'assenza di sottrazione. Non penso sia plausibile.

**Comment by criluc** [comment]
La mia spiegazione era solo la controprova che il dato fosse corretto.
Le ore positive sono sommate tra di loro, nient'altro. 
Faccia la somma delle differenze positive del mese, se non torna con 19:18 c'è un errore, ma lo dubito.

**Comment by DavFra94** [comment]
Capisco, grazie.
