### ISSUE TITLE
Inserimento di lavoro fuori sede via REST

### ISSUE THREAD

**Issue by lucanatalegov** [consiglionazionaledellericerche/epas#17]
E' possibile implementare una rest per l'iserimento del lavoro fuori sede per un determinato dipendente con Luogo, Motivazione e Note ?

**Comment by criluc** [comment]
Lo scrivo come documentazione per eventuali futuri interessati: questa possibilità è già disponibile, vedi https://consiglionazionaledellericerche.github.io/epas/rest/stampingsServices.html
