### ISSUE TITLE
Limiti orari missioni importati dal portale missioni

### ISSUE THREAD

**Issue by enricovillagrossi** [consiglionazionaledellericerche/epas#180]
Buonasera, 

chiedo un chiarimento sugli orari di inizio e fine missione importati dal portale missioni: ho notato che ePAS importando le missioni dal portale missioni "taglia" l'orario della missione forzandone l'inizio alle 7.00 e la fine alle 19.00 indipendentemente che sul portale missioni si sia inserito un orario di inizio antecedente le 7.00 o un orario di fine successivo alle 19.00.
Qual è la motivazione per questi limiti? E' un'impostazione di default o può essere configurata? L'ammistrazione del mio istituto non ha saputo darmi risposte.
Grazie in anticipo.

Enrico

**Comment by criluc** [comment]
Buongiorno @enricovillagrossi,
c'è un impostazione predefinita **Intervallo di attività lavorativa in sede per giorni missione** che ogni sede può personalizzare, può farlo il personale della sede con i diritti di "Amministratore del personale" su ePAS.
Questo comportamento mira a trattare il caso di medio ed è stata concordata con l'Ufficio delle Risorse Umane del CNR, altri casi possono comunque essere trattati in varie modalità (tra cui la modifica di quell'impostazione).
La documentazione del comportamento e della configurazione è qui: https://consiglionazionaledellericerche.github.io/epas/missions/index.html

**Comment by enricovillagrossi** [comment]
Grazie mille per la veloce risposta.
Enrico
