### ISSUE TITLE
Profili orari su periodi di più settimane

### ISSUE THREAD

**Issue by lucanatalegov** [consiglionazionaledellericerche/epas#185]
Buongiono,
Nella nosta organizzazioni ci sono persone in part-time su piu settimane.
per esempio
        50% di lavoro cosi distribuito 36 ore su quattro giorni una settimana e la seconda settimana la persona non lavora
        48% di lavoro 9 ore di lunedi 1:36 tutti i giorni e ogni 4 settimane 9 ore di mercoledi
        

In generale come possimo gestire orari di lavoro part-time che si completano su più settimane?

Grazie
Luca

**Comment by darietto1983** [comment]
Buon pomeriggio Luca,
i part time ciclici e spuri non vengono gestiti su ePAS. Questo perché Il sistema prevede la possibilità di definire l'orario di lavoro su base settimanale e non su base mensile, basandosi su quelle che sono le direttive del contratto che esplicita il calcolo sulle ore medie settimanali fatte dal dipendente.
Al momento, se il part time è di tipo ciclico su uno o più mesi e ci sono settimane (o anche mesi interi) in cui un dipendente non lavora, noi suggeriamo l'utilizzo dell'orario normale per le settimane in cui il dipendente lavora e di utilizzare il codice "NC" per le settimane in cui il dipendente non lavora.
Naturalmente in questo caso deve anche essere modificato il piano ferie associato al dipendente che non godrà più del "28+4" o "26+4" ma dovrà essere selezionato quello consono alla quantità oraria lavorata.


Saluti
