### ISSUE TITLE
Nessun ruolo può inserire i badge di un impiegato

### ISSUE THREAD

**Issue by lucanatalegov** [consiglionazionaledellericerche/epas#188]
Nessun ruolo puo inserire il badge associati ad un impegato , compreso Gestori dell'anagrafica.

E' possibile limitare un solo badge per ogni impegato?

Grazie Mille

**Comment by criluc** [comment]
I badge possono essere inserti dagli utenti ruoli di "Amministratore Tecnico".

No, non è possibile limitare ad un solo badge per ogni impiegato perché nei nostri casi d'uso a volte un secondo badge può essere necessario, è comunque cura dell'amministratore tecnico gestire questi limiti e casi
