### ISSUE TITLE
Matricola Alfanumerica

### ISSUE THREAD

**Issue by lucanatalegov** [consiglionazionaledellericerche/epas#2]
Non è possibile inserire una matricola alfanumetrica.
L'inserimento con la rest e' possibile nella lista persons/list e' presente la matricola ma persons/edit?personId=<n>   il campo è vuoto

**Comment by criluc** [comment]
ok, grazie della segnalazione. La matricola è internamente alfanumerica ma i campi input nelle form web sono rimasti type="number". Saranno corretti a partire dalla versione 2.6.1.

**Comment by criluc** [comment]
E disponibile la versione 2.6.1 con questa correzione.
