### ISSUE TITLE
Codici Assenza oraria

### ISSUE THREAD

**Issue by lucanatalegov** [consiglionazionaledellericerche/epas#20]
Nel caso in cui si venga scelto un coside di assenza orario che consente la maturazione del buono pasto questo non viede assegnato nonostante l' impiegato abbia concluo il suo orario di lavoro.
Questa anomalia si verifica anche sui cidici di assenza gia presente in ePAS vedi codice 92M.

**Comment by criluc** [comment]
Non tutti i codici di assenza oraria concorrono alla maturazione del buono pasto, questa è un'impostazione della codice stesso, nel caso di voglia modificare il comportamento predefinito si può agire modificando dall'interfaccia di modifica del codice di assenza il campo "Comportamento per buono pasto". 
Il sistema comprende un meccanismo di riallineamento dei codici di assenza che viene lanciato all'avvio dell'applicazione e che allinea i codici sul db con quelli presenti nel codice sorgente.
Se si vuole fare in modo che le modifiche effettuate via interfacce web non siano sovrascritte al riavvio dell'applicazione è necessario impostare a no anche il campo "Aggiornamento stato assenza".

Infine il codice 92M è stata recentemente oggetto di un cambiamento ed ha un comportamento eccezionale voluto dall'amministrazione CNR (vedi https://github.com/consiglionazionaledellericerche/epas/blob/main/app/manager/PersonDayManager.java#L573), per i livelli da I a III se il codice di Missione 92M è di oltre 4 ore allora non viene assegnato automaticamente il buono pasto, perché il personale può (al posto del buono) richiedere il rimborso del pasto nella richiesta di rimborso missione. 

L'amministrazione del personale può comunque forzare l'attribuzione del buono pasto per il giorno di missione oraria oltre le 4 ore (nel caso per esempio non sia stato richiesto il rimborso del pasto).

**Comment by lucanatalegov** [comment]
Ho configurato un profilo orario cone in figura un cosice di aasenza come in figura ho assegnato questo codice di assenza all'impiegato e ePAS non mi ha assegnato buono pasto.

Quale configurazione  non è corretta?

![profilio orario](https://github.com/consiglionazionaledellericerche/epas/assets/114504271/28943049-813a-4cc6-a0c2-b93ec99f0770)
![non attribuzione buono pasto](https://github.com/consiglionazionaledellericerche/epas/assets/114504271/aeee100c-b878-465a-9b02-929402c60ed6)
![codice assenza](https://github.com/consiglionazionaledellericerche/epas/assets/114504271/6ef2902f-2f52-4677-9786-926bd379f997)

**Comment by criluc** [comment]
Il comportamento indesiderato penso sia dovuto alla configurazione dell'orario di lavoro.
Soglia pomeridiano per buono pasto = 13:30 
Lavoro minimo per buono pasto dopo la soglia pomeridiana = 60
vuol dire che ci devono essere delle timbrature di lavoro per almeno 60 minuti dopo le 13:30, quindi almeno fino 14:30, nel giorno indicato le timbrature si fermano invece alle 14:29.

Il codice di assenza CONTO_STATO non viene considerato in questo conteggio minimo di 60 minuti dopo le 13:30 perché i codici di assenza non hanno assegnato un orario di inizio e fine ed il sistema non può sapere se quel lavoro è stato effettuato dopo le 13:30 o meno. 

Questo per il martedì e giovedì, invece per lunedì, mercoledì e venerdì avete 180 minuti minimi dopo la soglia di pausa pranzo pomeridiana (13:30), quindi ci devono essere timbrature almeno fino alle 16:30 (per un minino di tre ore) per avere il buono pasto, siete sicuri di voler questo comportamento?
