### ISSUE TITLE
Rimuovere la stampType del lavoro fuori sede dal menu a tendina presente nell'inserimento della timbratura

### ISSUE THREAD

**Issue by darietto1983** [consiglionazionaledellericerche/epas#209]
L'inserimento della timbratura deve avere come sole causali la pausa pranzo e i motivi i servizio
Il lavoro fuori sede deve essere disponibile solo nella scheda di inserimento a lui dedicata

**Comment by marcobaldiniinaf** [comment]
Ho installato nel nostro test la versione 2.19.1, ma la causale "Lavoro fuori sede" continua a vederla
![image](https://github.com/user-attachments/assets/8726471e-3462-4052-8647-91c9e8c8680d)
