### ISSUE TITLE
epas non si avvia dopo la migrazione dalla 2.15 a 2.17.1

### ISSUE THREAD

**Issue by lucanatalegov** [consiglionazionaledellericerche/epas#210]
Ho provato ad attivare la versione 2.17.1 partendo dalla versione 2.15.0 e epas non si attiva.

Allego il log esatratto con il comando docker service logs epas

epas_epasint.1.kgeuwhrtfikf@mit4me01    | ePas Protocol set to http
epas_epasint.1.kgeuwhrtfikf@mit4me01    | Backup del database non attivo.
epas_epasint.1.kgeuwhrtfikf@mit4me01    | Applico eventuali evoluzioni al database...
epas_epasint.1.kgeuwhrtfikf@mit4me01    | :: loading settings :: url = jar:file:/opt/play/play-1.5.3/framework/lib/ivy-2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
epas_epasint.1.kgeuwhrtfikf@mit4me01    | Jul 23, 2024 5:02:44 PM play.Logger info
epas_epasint.1.kgeuwhrtfikf@mit4me01    | INFO: Module secure is available (/home/epas/epas/modules/secure)
epas_epasint.1.kgeuwhrtfikf@mit4me01    | Jul 23, 2024 5:02:44 PM play.Logger info
epas_epasint.1.kgeuwhrtfikf@mit4me01    | INFO: Module shibboleth is available (/home/epas/epas/modules/shibboleth-1.2)
epas_epasint.1.kgeuwhrtfikf@mit4me01    | Jul 23, 2024 5:02:44 PM play.Logger info
epas_epasint.1.kgeuwhrtfikf@mit4me01    | INFO: Module fastergt is available (/home/epas/epas/modules/fastergt-1.10)
epas_epasint.1.kgeuwhrtfikf@mit4me01    | Jul 23, 2024 5:02:44 PM play.Logger info
epas_epasint.1.kgeuwhrtfikf@mit4me01    | INFO: Module pdf is available (/home/epas/epas/modules/pdf-0.9)
epas_epasint.1.kgeuwhrtfikf@mit4me01    | Jul 23, 2024 5:02:44 PM play.Logger info
epas_epasint.1.kgeuwhrtfikf@mit4me01    | INFO: Module lombok is available (/home/epas/epas/modules/lombok-1.2.5)
epas_epasint.1.kgeuwhrtfikf@mit4me01    | ~ Connected to jdbc:postgresql://mit4medb01:5432/db_epas
epas_epasint.1.kgeuwhrtfikf@mit4me01    | ~
epas_epasint.1.kgeuwhrtfikf@mit4me01    | ~ Your database default is in an inconsistent state!
epas_epasint.1.kgeuwhrtfikf@mit4me01    | ~
epas_epasint.1.kgeuwhrtfikf@mit4me01    | ~ While applying this script part:
epas_epasint.1.kgeuwhrtfikf@mit4me01    |
epas_epasint.1.kgeuwhrtfikf@mit4me01    | # --- Rev:217,Ups - dd250f5
epas_epasint.1.kgeuwhrtfikf@mit4me01    |
epas_epasint.1.kgeuwhrtfikf@mit4me01    | UPDATE working_time_types SET description = 'Allattamento fino a 31-06-2024', disabled = true WHERE description = 'Allattamento' and office_id is null;
epas_epasint.1.kgeuwhrtfikf@mit4me01    | INSERT INTO working_time_types (description, shift, meal_ticket_enabled, office_id, disabled, horizontal, version, enable_adjustment_for_quantity, external_id, updated_at)
epas_epasint.1.kgeuwhrtfikf@mit4me01    | VALUES ('Allattamento', false, false, null, false, true, 0, false, null, now());
epas_epasint.1.kgeuwhrtfikf@mit4me01    | INSERT INTO working_time_type_days (break_ticket_time, day_of_week, holiday, meal_ticket_time, time_meal_from, time_meal_to, time_slot_entrance_from,time_slot_entrance_to,
epas_epasint.1.kgeuwhrtfikf@mit4me01    | time_slot_exit_from, time_slot_exit_to, working_time, working_time_type_id, ticket_afternoon_threshold, ticket_afternoon_working_time, version, updated_at)
epas_epasint.1.kgeuwhrtfikf@mit4me01    | VALUES (0, 1, false, 0, 0, 0, 0, 0, 0, 0, 312, (select id from working_time_types where description = 'Allattamento' and office_id is null), 0, 0, 0, now());
epas_epasint.1.kgeuwhrtfikf@mit4me01    | INSERT INTO working_time_type_days (break_ticket_time, day_of_week, holiday, meal_ticket_time, time_meal_from, time_meal_to, time_slot_entrance_from,time_slot_entrance_to,
epas_epasint.1.kgeuwhrtfikf@mit4me01    | time_slot_exit_from, time_slot_exit_to, working_time, working_time_type_id, ticket_afternoon_threshold, ticket_afternoon_working_time, version, updated_at)
epas_epasint.1.kgeuwhrtfikf@mit4me01    | VALUES (0, 2, false, 0, 0, 0, 0, 0, 0, 0, 312, (select id from working_time_types where description = 'Allattamento' and office_id is null), 0, 0, 0, now());
epas_epasint.1.kgeuwhrtfikf@mit4me01    | INSERT INTO working_time_type_days (break_ticket_time, day_of_week, holiday, meal_ticket_time, time_meal_from, time_meal_to, time_slot_entrance_from,time_slot_entrance_to,
epas_epasint.1.kgeuwhrtfikf@mit4me01    | time_slot_exit_from, time_slot_exit_to, working_time, working_time_type_id, ticket_afternoon_threshold, ticket_afternoon_working_time, version, updated_at)
epas_epasint.1.kgeuwhrtfikf@mit4me01    | VALUES (0, 3, false, 0, 0, 0, 0, 0, 0, 0, 312, (select id from working_time_types where description = 'Allattamento' and office_id is null), 0, 0, 0, now());
epas_epasint.1.kgeuwhrtfikf@mit4me01    | INSERT INTO working_time_type_days (break_ticket_time, day_of_week, holiday, meal_ticket_time, time_meal_from, time_meal_to, time_slot_entrance_from,time_slot_entrance_to,
epas_epasint.1.kgeuwhrtfikf@mit4me01    | time_slot_exit_from, time_slot_exit_to, working_time, working_time_type_id, ticket_afternoon_threshold, ticket_afternoon_working_time, version, updated_at)
epas_epasint.1.kgeuwhrtfikf@mit4me01    | VALUES (0, 4, false, 0, 0, 0, 0, 0, 0, 0, 312, (select id from working_time_types where description = 'Allattamento' and office_id is null), 0, 0, 0, now());
epas_epasint.1.kgeuwhrtfikf@mit4me01    | INSERT INTO working_time_type_days (break_ticket_time, day_of_week, holiday, meal_ticket_time, time_meal_from, time_meal_to, time_slot_entrance_from,time_slot_entrance_to,
epas_epasint.1.kgeuwhrtfikf@mit4me01    | time_slot_exit_from, time_slot_exit_to, working_time, working_time_type_id, ticket_afternoon_threshold, ticket_afternoon_working_time, version, updated_at)
epas_epasint.1.kgeuwhrtfikf@mit4me01    | VALUES (0, 5, false, 0, 0, 0, 0, 0, 0, 0, 312, (select id from working_time_types where description = 'Allattamento' and office_id is null), 0, 0, 0, now());
epas_epasint.1.kgeuwhrtfikf@mit4me01    | INSERT INTO working_time_type_days (break_ticket_time, day_of_week, holiday, meal_ticket_time, time_meal_from, time_meal_to, time_slot_entrance_from,time_slot_entrance_to,
epas_epasint.1.kgeuwhrtfikf@mit4me01    | time_slot_exit_from, time_slot_exit_to, working_time, working_time_type_id, ticket_afternoon_threshold, ticket_afternoon_working_time, version, updated_at)
epas_epasint.1.kgeuwhrtfikf@mit4me01    | VALUES (0, 6, true, 0, 0, 0, 0, 0, 0, 0, 312, (select id from working_time_types where description = 'Allattamento' and office_id is null), 0, 0, 0, now());
epas_epasint.1.kgeuwhrtfikf@mit4me01    | INSERT INTO working_time_type_days (break_ticket_time, day_of_week, holiday, meal_ticket_time, time_meal_from, time_meal_to, time_slot_entrance_from,time_slot_entrance_to,
epas_epasint.1.kgeuwhrtfikf@mit4me01    | time_slot_exit_from, time_slot_exit_to, working_time, working_time_type_id, ticket_afternoon_threshold, ticket_afternoon_working_time, version, updated_at)
epas_epasint.1.kgeuwhrtfikf@mit4me01    | VALUES (0, 7, true, 0, 0, 0, 0, 0, 0, 0, 312, (select id from working_time_types where description = 'Allattamento' and office_id is null), 0, 0, 0, now());
epas_epasint.1.kgeuwhrtfikf@mit4me01    |
epas_epasint.1.kgeuwhrtfikf@mit4me01    |
epas_epasint.1.kgeuwhrtfikf@mit4me01    | ~ The following error occurred:
epas_epasint.1.kgeuwhrtfikf@mit4me01    |
epas_epasint.1.kgeuwhrtfikf@mit4me01    | ERROR: duplicate key value violates unique constraint "working_time_types_pkey"
epas_epasint.1.kgeuwhrtfikf@mit4me01    |   Detail: Key (id)=(4) already exists. [ERROR:0, SQLSTATE:23505]
epas_epasint.1.kgeuwhrtfikf@mit4me01    |
epas_epasint.1.kgeuwhrtfikf@mit4me01    | ~ Please correct it manually, and mark it resolved by running `play evolutions:resolve`
epas_epasint.1.kgeuwhrtfikf@mit4me01    | ~
epas_epasint.1.kgeuwhrtfikf@mit4me01    | ~        _            _
epas_epasint.1.kgeuwhrtfikf@mit4me01    | ~  _ __ | | __ _ _  _| |
epas_epasint.1.kgeuwhrtfikf@mit4me01    | ~ | '_ \| |/ _' | || |_|
epas_epasint.1.kgeuwhrtfikf@mit4me01    | ~ |  __/|_|\____|\__ (_)
epas_epasint.1.kgeuwhrtfikf@mit4me01    | ~ |_|            |__/
epas_epasint.1.kgeuwhrtfikf@mit4me01    | ~
epas_epasint.1.kgeuwhrtfikf@mit4me01    | ~ play! 1.5.3, https://www.playframework.com
epas_epasint.1.kgeuwhrtfikf@mit4me01    | ~ framework ID is prod
epas_epasint.1.kgeuwhrtfikf@mit4me01    | ~
opadmin@mit4me01:/app/mit4me$

**Comment by criluc** [comment]
Effettivamente ci sono alcuni casi in cui il passaggio dalla 2.15 alla 2.17.1 non funzionava a causa di alcuni casi non previsti nell'evoluzione del db 215.sql.
Per ripristinare lo stato del database è necessario lanciare questi due comandi dalla directory dove si trova il docker-compose.yml:
 - docker-compose run epas app:play evolutions:resolve
 - docker-compose run epas app:play evolutions:apply

questi due comandi dovrebbero ripristinare lo stato del db ignorando l'evoluzione critica.

**Comment by lucanatalegov** [comment]
Dopo queste operazioni consentiranno di usare la versione 2.17.1 o occorrerà usare sempre la versione 2.15.0?

**Comment by criluc** [comment]
> Dopo queste operazioni consentiranno di usare la versione 2.17.1 o occorrerà usare sempre la versione 2.15.0?

Si, permetterà di usare la 2.7.1

**Comment by criluc** [comment]
Non sembra un problema di epas ma di docker, sembra che l comando docker-compose non riesca a comunicare con il server docker.
Forse per avviarlo usi il plugin di docker? 
In questo caso devi utilizzare "$ docker compose run ..." invece "$ docker-compose run ..."
