### ISSUE TITLE
residui orari

### ISSUE THREAD

**Issue by lucanatalegov** [consiglionazionaledellericerche/epas#22]
E' possibile limitare il "Residuo dai mesi precedenti" ad un numero di minuti definiti ( per esempio 300 minuti) questa limitazione scatta a partire da un determinato giorno del mese in corso in modo tale che l'ufficio e l'impiegato ni proimi giorni del mese possono chiedere l'assegnazione di una competnza.

per esempio se  Residuo dai mesi precedenti è 420 minuti se l'impiegato entro il 15 del mese in corso non chiede una determinata competenze a pertire dal 16 il Residuo dai mesi precedenti  scende a 300 e viede data evidenza che 120 sono stati persi perche non è stata chiesta nessuna competenza.

Grazie

**Comment by lucanatalegov** [comment]
Vorrei descrivere meglio la mia richiesta:
nel caso in cui i "Residuo dai mesi precedenti" sia superiore ad un limite configiurabile deve essere possibile, entro una certa data, chiedere  o il pagamento dell' eccedente o farlo confluire in una banca ore da cui attingere per i riposi compensativi i quali devono essere presi entro N mesi.
nel caso in cui il "Residuo dei mesi precedenti sia negativo va recuperato nel mese in corso

Grazie

**Comment by criluc** [comment]
Adesso ci sono già dei meccanismi simili ma che potrebbero differire su diversi aspetti non semplici da conciliare.

Al momento tutte le ore fatte in più nel tempo vanno a finire in quello che in ePAS viene chiamato monte ore residue (che corrisponde penso alla banca ora sopra citata). 
Questo monte ore non ha scadenza per i livelli I-III, mentre per i livelli > III queste ore possono essere utilizzate fino all'anno successivo (di default entro il 31/03 ma questa data può essere configurata per sede).
Il monte ore può essere utilizzato per recuperare l'orario in giornate in cui si è fatto meno orario del previsto, oppure come riposi compensativi giornalieri, inoltre è possibile inserire gli straordinari che vanno anche questi a decurtare il monte ore.
Per quanto riguarda gli straordinari al momento è possibile inserirli come "competenza" solo da parte dell'amministratore del personale, però stiamo lavorando a dei flussi di richiesta straordinario.
Infine per l'obbligo di recuperare eventuali residui negativi, l'unica cosa che ePAS potrebbe fare è quello di mandare una notifica (al responsabile di sede?), su questo potremo lavorarci ma andrebbe resa configurabile per andare incontro anche ai casi d'uso del EPR, quindi eventualmente da decidere in una issue separata.

Per adesso lascio la issue aperta ma per adesso non abbiamo risorse per metterla in programmazione nelle prossime milestone recenti.
