### ISSUE TITLE
Mancata riduzione del residuo ore

### ISSUE THREAD

**Issue by lucanatalegov** [consiglionazionaledellericerche/epas#23]
Ho notato che nonostante abbia creato una competenza e un gruppo di competenza ( entrambi con unità di misura oraria ed entrambe senza limite) ho abbilitato questa competenza su un impegato e ho assegnatao a questa competenza un certo numero di ore.

Ho notato che il residuo ore, presente nel riepilogo delle timbrature,  non diminure e non mi compare nessuna voce aggiuntiva nel Riepilogo Ore.
Se invece , dopo aver assegnato all'impiegato la competenza S1, associo delle ore alla competenza S1 il Residuo ore cambia e cambia anche il Piepilogo Ore con lo straordinario inserito.

**Comment by criluc** [comment]
Il comportamento è quello previsto da ePAS, cioè solo gli straordinari (le competenze individuate con i codici S1, S2, S3) vanno a decurtare il monte orario.
Le altre competenze sono tipicamente riconoscimenti economici che non riguardano direttamente l'orario di lavoro fatto in più (per esempio indennità di sede disagiata, di rischio, di mansione, di turno, etc).
Le indennità che devono riportare ad una diminuzione del monte orario forse andrebbero ricondotte ad una delle tipologie di straordinario già presenti.
