### ISSUE TITLE
Posibilià di iserire sull'anagrafica del dipendente altri dati

### ISSUE THREAD

**Issue by lucanatalegov** [consiglionazionaledellericerche/epas#237]
Sara' possibile inserire sull' anagrafica del dipendente altri dati come Titolo e abilitazioni.

**Comment by criluc** [comment]
Non sarà possibile, l'idea è quella di tenere in ePAS solo i dati relativi alla gestione delle presenze/assenze, non di utilizzarlo come anagrafica del personale.
