### ISSUE TITLE
Nuove rest

### ISSUE THREAD

**Issue by lucanatalegov** [consiglionazionaledellericerche/epas#24]
E' possibile avere una rest che esporta il residuo delle ore per un determinato mese per un determinato impiegato o  per tutti gli impiegati di una sede?

E' possibile avere una rest per assegnare ad una competenza un valore e delle note per un determinato impiegato se a questo è stata assegnata quella competenza.

**Comment by criluc** [comment]
Per quanto riguarda la prima richiesta, c'è un endpoint REST che mostra tutta la situazione mensile di un dipendente nella nuova versione del backend di epas che stiamo sviluppando e che trovi qui: https://github.com/consiglionazionaledellericerche/epas-service

Le richieste di nuovi servizi REST al momento abbiamo deciso di implementarle sul nuovo progetto, prova a vedere quello che già c'è disponibile ed eventualmente apri una issue sul nuovo progetto.
