### ISSUE TITLE
Il permesso orario 661G non giustifica l'intero giorno di lavoro

### ISSUE THREAD

**Issue by lucanatalegov** [consiglionazionaledellericerche/epas#240]
Il codice 661G  , nel caso di orarri di lavoro diverso da "Normale", decurta le ore previste dal orario invece di 6 ore convenzionalmente previste
Esempio : nel caso in cul la giornata lavorativa sia di 9 ore l'appilcazione del codice 661G sottae 9 ora dal totale previsto invece di 6.

**Comment by darietto1983** [comment]
Ciao Luca, secondo la nostra amministrazione centrale il comportamento è corretto specialmente in relazione a quei part time verticali che presentano giornate, ad esempio, di 9 ore e altre di 3 ore. A seconda della giornata in cui viene preso il 661G occorre decurtare dal monte ore disponibile la quantità oraria che il dipendente avrebbe dovuto lavorare quel giorno.
