### ISSUE TITLE
Possibilita di inserire un "Codice di Assenza" con giustificazione negativa

### ISSUE THREAD

**Issue by lucanatalegov** [consiglionazionaledellericerche/epas#246]
Possibilita di inserire un "Codice di Assenza" con giustificazione negativa al fine di ridurre il "Residuo" a fronte di un lavoro non autorizzato.

Occorrerebbe modificare anche la  "Differenza" e il "Tempo Lavoro"

**Comment by lucanatalegov** [comment]
Ho provato e , ovviamente, funziona

Ma non funziona tramite la rest, stiamo mettendo a punto una procedura che dovrebbe fare queste operazioni in automatico.


8.1.4. Inserimento nuova assenza


/rest/absences/insertAbsence

anche se metto minutes negativo non riduce nulla.


Come posso risolvere il problema.

Grazie Mille



________________________________
Da: Cristian Lucchesi ***@***.***>
Inviato: mercoledì 23 ottobre 2024 16:24
A: consiglionazionaledellericerche/epas ***@***.***>
Cc: Natale Luca ***@***.***>; Author ***@***.***>
Oggetto: Re: [consiglionazionaledellericerche/epas] Possibilita di inserire un "Codice di Assenza" con giustificazione negativa (Issue #246)


Una soluzione che potete già sperimentare in autonomia potrebbe essere quella di crearvi un nuovo codice a uso interno che non giustifica niente

Tipo questo:

image.png (view on web)<https://github.com/user-attachments/assets/9c1f0cf5-e40c-42a4-b542-be70d777c309>

Inserire poi questo nuovo codice in un gruppo di assenze, come per esempio "Altri codici" e poi inserirlo nei giorni che dove vi interessa decurtare l'orario.

Il codice da solo non decurterà niente ma nella scheda "Ore in più" potete inserire un valore positivo o negativo per cambiare sia la "Differenza" che il "Tempo a lavoro", tipo così:

image.png (view on web)<https://github.com/user-attachments/assets/a28f6d9f-2423-4433-a49c-a841f0393a98>

**Comment by criluc** [comment]
Se volete gestire questi codici via REST alla potresti utilizzare un piccola variante alla prima proposta.

Nella definizione del nuovo codice impostate "Tipo di giustificazione permessa" a "Specificare ore e minuti", così facendo le ore e i minuti non verranno ignorati e potete passarli durante l'inserimento dell'assenza via REST.

Non vi avevo segnalato prima questa soluzione perché via interfaccia WEB non è permesso di inserire valori negativi per le ore e i minuti di un'assenza, ma facendolo via REST non avete questa limitazione e dovrebbe funzionarvi tutto il giro.

Se volete dare anche la possibilità di inserire via WEB un codice con valori negativi allora dovete avere anche un codice come il primo che vi avevamo proposto, in quel caso però i valori di "Ore in più per assenza" non sono per adesso controllabili via REST.
