### ISSUE TITLE
Uscite di servizio

### ISSUE THREAD

**Issue by lucanatalegov** [consiglionazionaledellericerche/epas#25]
Buongiorno

Abbiamo attivato il flusso “Uscite di servizio” e abbiamo inserito delle richieste di questo tipo.  Nonostante siano state autorizzate dal responsabile di gruppo ( per il responsabile di sede abbiamo disattivato questa funzionalità)  sul cartellino non era presente nessuna informazione a riguardo e l’ assenza non era giustificata.

**Comment by criluc** [comment]
Le uscite di servizio in ePAS sono solo flussi informativi, ovvero non hanno effetto sui calcoli del sistema e non inseriscono ne timbrature, ne assenze. In particolare la richiesta di uscita di servizio può essere utilizzata per ottenere l'autorizzazione preventiva dal proprio responsabile, indicando un orario indicativo.
L'orario preciso dell'uscita di servizio (e la conseguente timbratura nel sistema) e però gestito tramite la causale da selezionare sul lettore al momento dell'uscita dal lavoro del dipendente. Cioè il dipendente quando effettivamente esce deve timbrature con la causale corretta e se il client è configurato opportunamente, la timbratura viene inserita come uscita di servizio ed i calcoli del tempo a lavoro fatti di conseguenza.
