### ISSUE TITLE
Rimozione codice di assenza

### ISSUE THREAD

**Issue by lucanatalegov** [consiglionazionaledellericerche/epas#253]
Se in un determinato giorno ci sono più giustificativi con lo **stesso codice** nel caso in cui si voglia rimuovere uno solo di questi codici il sistema li rimuove tutti anche quello non selezionato ( cioè non rimuove l'assenza in base all' id della stessa ma in base al codice)

**Comment by criluc** [comment]
Il comportamento attuale è un compromesso che abbiamo valutato a suo tempo per far si di poter rimuove più codici contemporaneamente cioè per più giorni.
Dall'altra parte non c'è una relazione tra i codici di più giorni e anche selezionando un codice (un id) specifico, per i giorni successivi in caso di più codici uguali non sapremo quale togliere.
Quindi togliere tutti i giustificati con lo stesso codice è l'attuale compromesso a cui si sono abituati gli utilzzatori di ePAS.
