### ISSUE TITLE
Giustificativo Ritardo 

### ISSUE THREAD

**Issue by lucanatalegov** [consiglionazionaledellericerche/epas#28]
E’ possibile inserire una giustificativo di assenza “Ritardo” che  sia simile al ”Permesso Breve” ma a differenza di questo non  abbia 36 ore massime e sia usato solo per giustificare le assenza tra la fascia di presenza alla prima timbratura se questa e successiva.
Esempio:
se la fascia di presenza è 08:45 alle 12:45
se la prima timbratura ( ingresso) e alle 09:00 allora c’e un ritardo di 15 minuti ed è aggiornato il Residuo del mese positivo
se la prima timbratura (ingresso)  è alle 08:30 e poi c’e un uscita alle 08:40 e un secondo ingresso alle 09:00 allora c’e un permesso di 20 minuti.

**Comment by criluc** [comment]
Al momento non è prevista nessuna funzionalità del genere. Negli attuali casi d'uso va in contrasto con la gestione del permesso breve.
