### ISSUE TITLE
Possibilia di associare piu' gruppi badge ad una persona

### ISSUE THREAD

**Issue by lucanatalegov** [consiglionazionaledellericerche/epas#3]
Non è possibile fare  associare piu gruppi badge ad una persona.

**Comment by darietto1983** [comment]
La relazione tra persona e gruppo badge non è diretta. Il gruppo badge è un'entità relazionata con la sede di afferenza del dipendente (Office) attraverso una relazione "uno a molti". Il gruppo badge presenta a sua volta una relazione "uno a molti" con l'entità Badge (ovvero il pool di badge assegnati ai dipendenti di una sede).
Definendo più gruppi badge per una sede è possibile quindi, di conseguenza, assegnare più badge alla stessa persona (scegliendoli appunto tra quelli associati alla sede di afferenza del dipendente).

**Comment by lucanatalegov** [comment]
Il nostro problema che abbiamo personse che possono lavorare su più sedi della stesso istituto o su istituti diversi e vorremmo poter gestire le timbrature di queste persone.


l'alternativa, che non vorremo attuare, e creare un solo gruppo badge per tutti le sedi.


Grazie

Luca


________________________________
Da: darietto1983 ***@***.***>
Inviato: giovedì 29 settembre 2022 09.55
A: consiglionazionaledellericerche/epas
Cc: Natale Luca; Author
Oggetto: Re: [consiglionazionaledellericerche/epas] Possibilia di associare piu' gruppi badge ad una persona (Issue #3)


La relazione tra persona e gruppo badge non è diretta. Il gruppo badge è un'entità relazionata con la sede di afferenza del dipendente (Office) attraverso una relazione "uno a molti". Il gruppo badge presenta a sua volta una relazione "uno a molti" con l'entità Badge (ovvero il pool di badge assegnati ai dipendenti di una sede).
Definendo più gruppi badge per una sede è possibile quindi, di conseguenza, assegnare più badge alla stessa persona (scegliendoli appunto tra quelli associati alla sede di afferenza del dipendente).

-
