### ISSUE TITLE
Nel si riesce a rimuove un permesso breve nella "Fascia oraria obbligatoria" nonostante ci sia un aluto giustificativo ( 631M)

### ISSUE THREAD

**Issue by lucanatalegov** [consiglionazionaledellericerche/epas#30]
Nel caso di assenza di un impiegato nella Fascia oraria obbligatoria il sistema assegna un permesso breve anche se è inserito un permesso orario visita medica in ore e minuti (631M) .
Nella posizione compaiono due giustificativi il PB e 631M.
Il permesso per malaittia 631M si riesce a rimuovere mentre il PB se lo rimuovo il sistema lo ricrea in automatico.

**Comment by criluc** [comment]
Inseriremo una nuova funzionalità che permette di disabilitare il calcolo del permesso breve in un giorno specifico, così da gestire casi particolari come questo.
