### ISSUE TITLE
Inserimento assenze piu vecchie di un anno

### ISSUE THREAD

**Issue by lucanatalegov** [consiglionazionaledellericerche/epas#32]
E' possibile modificare il comportamento di ePAS per inserire  assenze più vecchie di un anno.
Sia da Gui che da REST

**Comment by criluc** [comment]
Ogni assenza inserita nel passato comporta, per la persona relativa all'assenza, il ricalcolo della situazione giornaliera di tutti i giorni dalla data dell'assenza inserita fino alla data odierna.
Questa operazione può essere quindi molto lenta, specialmente andando molto nel passato e può caricare molto il sistema.
Abbiamo reso configurabile il numero massimo di mesi nel passato ma va usata con parsimonia per le limitazioni di cui sopra.
