### ISSUE TITLE
comportamento assenza per malattia prolungate

### ISSUE THREAD

**Issue by lucanatalegov** [consiglionazionaledellericerche/epas#33]
Come si comporta ePAS in caso in cui un impegato superi le assenza per malattia.
Per esempio se un impegato supera i 12 mesi  di malattia viene bloccato il codice 111 e sono proposti gli altri codici  (vedi 115) o è tutto automantico

**Comment by darietto1983** [comment]
In questo momento ePAS non adotta un comportamento di limitazione sui giorni di malattia presi dai dipendenti. Non ci sono vincoli quantitativi implementati
