### ISSUE TITLE
autenticazione ldap

### ISSUE THREAD

**Issue by lucanatalegov** [consiglionazionaledellericerche/epas#4]
E' possibile indicare che una persona puo accedere utilizzando l'autenticazione ldap o autenticazione interna.
E possibile creare una pagina di login con un unico form in cui in base all'utente il sistema utilizzi o autenticazione ldap o interna
Nel caso di autenticazione ldap occorre poter definire un url esterna per la procedura di reset password.

**Comment by criluc** [comment]
L'attuale modalità di autenticazione è ispirata e gitlab ed i nostri utenti ci sono già abituati da tempo.
Inoltre a me non piace mescolare le due autenticazioni in un'unica form, perché l'utente non sa mai con quale password sta entrando, se quella ldap o quella locale, generando false supposizioni sul sistema di autenticazione.
Quindi non unificheremo la form di autenticazione ma lasceremo le tab come adesso.

Invece per la url esterna per la procedura di recupero della password LDAP si può anche prevedere, vediamo di inserirla come enhancement nelle prossime release.

**Comment by criluc** [comment]
Nella versione 2.6.1 è stata introdotto la possibilità di specificare nel docker-compose.yml il parametro LDAP_PASSWORD_RECOVERY_URL.
