### ISSUE TITLE
Inserimento delle timbrature antecedenti alla data di installazione 

### ISSUE THREAD

**Issue by lucanatalegov** [consiglionazionaledellericerche/epas#6]
E' possibile inserire le timbrature antecedenti alla data di installazione?
Nella nostra installazione questo non è stato possibile.

Grazie Mille

**Comment by darietto1983** [comment]
Buon pomeriggio,
questa possibilità non è prevista in primo luogo perchè risulta computazionalmente oneroso inserire timbrature che vanno parecchio indietro nel tempo e che comportano i ricalcoli degli orari delle giornate successive alla data di inserimento della timbratura, e poi perchè è verosimile che l'inserimento di timbrature precedenti all'utilizzo di ePAS comportino un calcolo che risulterebbe diverso rispetto a quello fatto nel precedente sistema di gestione del personale utilizzato creando evidenti incongruenze.
L'utilizzo della funzionalità di inizializzazione oraria ha proprio lo scopo di mettere un punto di partenza alla situazione quando si inizia a usare ePAS di modo che fino a quella data i valori in termini di orario e residuo siano "acquisiti" e che da quel momento in poi con l'algoritmo di calcolo del tempo a lavoro i conteggi siano quelli corretti.
