### ISSUE TITLE
Gestione automatica verso timbratura

### ISSUE THREAD

**Issue by lucanatalegov** [consiglionazionaledellericerche/epas#7]
E' possibile definire un opzione sul' utente in modo tale che la prima timbratura del giorno sia un ingresso e la seconda sia un uscita o più in generale la timbratura dispari sia l'ingresso mentre la timbratura pari sia l'uscita.
 
Grazie Mille

**Comment by criluc** [comment]
In passato abbiamo provato ad inserire euristiche di questo tipo ma con scarso successo. Per non complicare ulteriormente la parte server però possiamo pensare di inserire questa logica nel client. In questo modo il client specifico deciderà la logica per definire il verso delle timbrature. Quale client di ePAS state utilizzando per inviare le timbrature? Magari facciamo una issue direttamente su quello.

**Comment by lucanatalegov** [comment]
Non usiamo nessun client, ho costruito una script che prima di fare la rest fa dei controlli utilizzano le rest messe a disposizione dalla piattaforma.
