### ISSUE TITLE
Calcolo buoni pasto in casi di ingressi e uscite

### ISSUE THREAD

**Issue by marcobaldiniinaf** [consiglionazionaledellericerche/epas#72]
![Screenshot 2023-10-06 161636](https://github.com/consiglionazionaledellericerche/epas/assets/108818348/7bbeed19-9ebf-4af8-9204-5ea0f11dffcd)

Non capiamo perchè non ha calcolato il buono pasto, ha superato le 6h è uscita per più di 30', ma non ha assegnato il buono pasto

**Comment by darietto1983** [comment]
Ciao Marco, le segnalazioni relative a calcoli che non tornano o "strani" mandale pure da dentro ePAS usando il tasto "invia segnalazione" così possiamo vedere nel dettaglio il cartellino del dipendente che ha avuto il problema
