### ISSUE TITLE
Gestione dei dipendenti per area e fascia economica

### ISSUE THREAD

**Issue by lucanatalegov** [consiglionazionaledellericerche/epas#8]
E' possibile definire i ruoli del personale in base al area e fascia economia in alternativa ai livelli con la relativa gestione?

Grazie Mille

**Comment by darietto1983** [comment]
Buon pomeriggio,
ci interesserebbe capire come funziona il concetto di fascia economica e di area. Questo perchè immaginiamo che, come i livelli nell'attuale implementazione, abbiano delle influenze sugli algoritmi di calcolo degli orari di lavoro o di mantenimento dei residui orari o di utilizzo di certi codici di assenza ecc...
Se così fosse sarebbe ovviamente interessante implementare il tutto

**Comment by lucanatalegov** [comment]
Buongiorno,

Nel nostro contratto ci sono 3 are all'interno di queste ci sono varie fasce economiche.
A livello di ferie, permessi, assenza le tre are sono uguali.
L'assegnazione all'area corretta non comporta nessun beneficio particolare.

Grazie Mille
Luca
