### ISSUE TITLE
endpoint REST getmonthsituationbyoffice

### ISSUE THREAD

**Issue by khekkosan** [consiglionazionaledellericerche/epas#81]
Buongiorno, 
stiamo usando l'endpoint REST **getmonthsituationbyoffice** a cui aggiungiamo i parametri _sedeID, year, month_ e ci siamo accorti che oltre a restituire le informazioni per il personale attivo, restituisce anche quelle relative al personale non più attivo.

**Comment by criluc** [comment]
Buon pomeriggio,
immagino tu ti riferisca all'endpoint REST **/v3/persondays/getmonthsituationbyoffice** (ma è praticamente uguale per la **/v2**.
Quell'endpoint preleva i dati di tutti i riepiloghi delle persone presenti in quel mese, la chiamata per prelevare i dettagli giornalieri (PersonDay) è qui https://github.com/consiglionazionaledellericerche/epas/blob/main/app/controllers/rest/v3/PersonDays.java#L127
dopo di che nelle righe successive crea una mappa dove ci sono tutte le persone che hanno almeno un riepilogo giornaliero in quel mese.

Detto in altre parole se una persona con un contratto non più attivo ha comunque una timbratura, una missione o un'altra qualunque assenza (e di conseguenza un PersonDay)  nel mese che stiamo consultando, allora comparirà nel riepilogo mensile. 
Questo mi sembra corretto, se ci sono altri casi non contemplati facci sapere.
