### ISSUE TITLE
Disabilitare "Invia Segnalazione"

### ISSUE THREAD

**Issue by lucanatalegov** [consiglionazionaledellericerche/epas#9]
Il nostro contesto prevede una organizzazione a più livelli e vorremmo evitare che arrivassero segnalazione da chiunque possa acedere a ePAS ma vorremmo essere contattati solo da alcuni utenti tramite  una mail tradizionali senza usare la funzionalita di "Invia segnalazione"

E' possibile eliminare il Button "Invia Segnalazione" nel caso in cui non siano presenti le variabili

REPORT_TO e/o REPORT_FROM

Grazie Mille

**Comment by criluc** [comment]
Al momento ePAS è già configurato per lavorare a livelli, nel senso che le segnalazioni dei dipendenti arrivano via email agli amministratori del personale o tecnici della propria sede (in funzione del fatto che la segnalazione sia per problemi amministrativi o tecnici).
In questo modo nelle varie sede possono risolvere le varie questioni sollevate dai dipendenti in modo locale, dove di solito risiedono le informazioni specifiche di quel dipendente.
Invece le segnalazioni degli amministratori del personale o tecnici arrivano all'indirizzo email configurato tramite il parametro presente nel docker-compose.yml REPORT_TO=${REPORT_TO}.

Con questa modalità riusciamo a gestire ~300 sedi del CNR con ~8000 dipendenti con uno strumento integrato per le segnalazioni che permette di catturare maggiori informazioni sulle segnalazione (testo, immagine della pagina corrente, indirizzo, variabili di sessione, etc).

@lucanatalegov questa modalità è sufficiente oppure preferiste disattivare comunque la possibilità di inviare le segnalazioni? In quel caso però non avreste nessun controllo sulla gerarchia spiegata sopra.
