### ISSUE TITLE
Errore in creazione missione oraria in un giorno festivo

### ISSUE THREAD

**Issue by marcobaldiniinaf** [consiglionazionaledellericerche/epas#90]
Abbiamo riscontrato un problema nell'invio di una missione tramite API, riscontrato anche da interfaccia
Un utente vuole fare una missione dal 2/12 all'8/12 (festività che cade di venerdì) con fine alle 9:00.
l'8/12 però tramite API non ha creato la missione oraria e ha mandato l'errore tramite email.
Tramite interfaccia il messaggio dice che ignora la missione perchè giorno festivo
![image](https://github.com/consiglionazionaledellericerche/epas/assets/108818348/997e150b-608d-4b84-92ea-78181aa8956a)

**Comment by criluc** [comment]
ok abbiamo riprodotto il problema, non è previsto che si possa mettere una missione oraria durante i festivi e trovando questa incongruenza il sistema non inserisce nemmeno gli altri giorni di missione.
Probabilmente almeno gli altri giorni dovrebbe inserirli, oppure forse permettere di inserire i 92M nei festivi.
Faremo qualche verifica per trovare la soluzione migliore per sistemare questo comportanto.
